-- MD. Shoriful Islam (Sakib) Dynamic Portfolio
-- Run once in Supabase -> SQL Editor.
-- Then create ONE admin user in Authentication -> Users.
-- IMPORTANT: Disable public user signups in Auth settings before going live.

create table if not exists public.profile (
  id bigint primary key default 1 check (id = 1),
  full_name text not null default 'MD. Shoriful Islam (Sakib)',
  short_name text default 'Sakib',
  headline text default 'Creative Developer & Digital Problem Solver',
  hero_text text,
  about_title text,
  bio text,
  availability text default 'Available for opportunities',
  location text default 'Bangladesh',
  email text,
  phone text,
  avatar_url text,
  resume_url text,
  github_url text,
  linkedin_url text,
  facebook_url text,
  years_experience text default '2+',
  projects_count text default '15+',
  clients_count text default '10+',
  updated_at timestamptz default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  tech_stack text,
  category text default 'Web App',
  image_url text,
  live_url text,
  github_url text,
  featured boolean default false,
  sort_order integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  category text default 'Frontend',
  level integer default 80 check (level between 0 and 100),
  sort_order integer default 0
);

create table if not exists public.experiences (
  id bigint generated by default as identity primary key,
  title text not null,
  organization text,
  period text,
  description text,
  sort_order integer default 0
);

create table if not exists public.education (
  id bigint generated by default as identity primary key,
  degree text not null,
  institution text,
  period text,
  description text,
  sort_order integer default 0
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  icon text default 'code',
  description text,
  sort_order integer default 0
);

create table if not exists public.certifications (
  id bigint generated by default as identity primary key,
  title text not null,
  issuer text,
  year text,
  credential_url text,
  sort_order integer default 0
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  quote text,
  avatar_url text,
  sort_order integer default 0
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (char_length(email) between 3 and 180),
  subject text not null check (char_length(subject) between 1 and 160),
  message text not null check (char_length(message) between 1 and 4000),
  created_at timestamptz default now()
);

insert into public.profile (id, full_name, short_name, headline, hero_text, about_title, bio, location)
values (
  1,
  'MD. Shoriful Islam (Sakib)',
  'Sakib',
  'Creative Developer & Digital Problem Solver',
  'I design and build modern, fast and memorable digital experiences with clean code, thoughtful UI and a strong focus on usability.',
  'Building digital products with purpose and personality.',
  'I enjoy turning ideas into polished web experiences. Update this text with your real biography from the Admin Panel.',
  'Bangladesh'
)
on conflict (id) do nothing;

insert into public.services (title, icon, description, sort_order)
select * from (values
  ('Frontend Development','code','Fast, responsive and maintainable interfaces built around real user needs.',1),
  ('Full-stack Web Apps','layers','Database-backed applications with authentication, storage and admin workflows.',2),
  ('UI Implementation','sparkles','Pixel-conscious implementation of modern layouts, motion and interaction design.',3)
) as v(title,icon,description,sort_order)
where not exists (select 1 from public.services);

insert into public.skills (name, category, level, sort_order)
select * from (values
  ('React','Frontend',90,1),('JavaScript','Frontend',88,2),('Responsive UI','Frontend',92,3),
  ('Supabase','Backend',82,4),('REST API','Backend',84,5),('Git & GitHub','Tools',88,6)
) as v(name,category,level,sort_order)
where not exists (select 1 from public.skills);

alter table public.profile enable row level security;
alter table public.projects enable row level security;
alter table public.skills enable row level security;
alter table public.experiences enable row level security;
alter table public.education enable row level security;
alter table public.services enable row level security;
alter table public.certifications enable row level security;
alter table public.testimonials enable row level security;
alter table public.messages enable row level security;

-- Public can read portfolio content.
create policy "public read profile" on public.profile for select to anon, authenticated using (true);
create policy "public read projects" on public.projects for select to anon, authenticated using (true);
create policy "public read skills" on public.skills for select to anon, authenticated using (true);
create policy "public read experiences" on public.experiences for select to anon, authenticated using (true);
create policy "public read education" on public.education for select to anon, authenticated using (true);
create policy "public read services" on public.services for select to anon, authenticated using (true);
create policy "public read certifications" on public.certifications for select to anon, authenticated using (true);
create policy "public read testimonials" on public.testimonials for select to anon, authenticated using (true);

-- Authenticated admin can manage portfolio content.
create policy "admin manage profile" on public.profile for all to authenticated using (true) with check (true);
create policy "admin manage projects" on public.projects for all to authenticated using (true) with check (true);
create policy "admin manage skills" on public.skills for all to authenticated using (true) with check (true);
create policy "admin manage experiences" on public.experiences for all to authenticated using (true) with check (true);
create policy "admin manage education" on public.education for all to authenticated using (true) with check (true);
create policy "admin manage services" on public.services for all to authenticated using (true) with check (true);
create policy "admin manage certifications" on public.certifications for all to authenticated using (true) with check (true);
create policy "admin manage testimonials" on public.testimonials for all to authenticated using (true) with check (true);

-- Anyone can send a message, but only authenticated admin can read/delete messages.
create policy "public send messages" on public.messages for insert to anon, authenticated with check (true);
create policy "admin read messages" on public.messages for select to authenticated using (true);
create policy "admin delete messages" on public.messages for delete to authenticated using (true);

-- Public storage bucket for portfolio images and CV.
insert into storage.buckets (id, name, public, file_size_limit)
values ('portfolio', 'portfolio', true, 10485760)
on conflict (id) do update set public = true, file_size_limit = 10485760;

create policy "public read portfolio files"
on storage.objects for select to anon, authenticated
using (bucket_id = 'portfolio');

create policy "admin upload portfolio files"
on storage.objects for insert to authenticated
with check (bucket_id = 'portfolio');

create policy "admin update portfolio files"
on storage.objects for update to authenticated
using (bucket_id = 'portfolio') with check (bucket_id = 'portfolio');

create policy "admin delete portfolio files"
on storage.objects for delete to authenticated
using (bucket_id = 'portfolio');
