services:
  - type: web
    name: sakib-portfolio
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
